import Head from "next/head";

type Props = {
  title?: string;
  children: React.ReactNode;
};

const Container = ({ title = "Next.js with tRPC", children }: Props) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>{children}</main>
    </>
  );
};

export default Container;
